### ISSUE TITLE
Resume Functionality

### ISSUE THREAD

**Issue by winstonpinto12** [dhodges47/SCORM-LearningManagementSystem#10]
Hi,

Is there a functionality wherein it resumes from the point it stopped  last? Also I have a SCORM on which next button is enabled once all content is loaded but this is not getting enabled, any input where can i check for this issue and how to fix it?

**Comment by dhodges47** [comment]
1. The capability to resume is built right into SCORM. The SCORM package sends a field called "SuspendData" when it closes. When the session resumes again it requests SuspendData from the server and uses it to resume the course.
HOWEVER I discovered a bug in the implementation of that, so I'll commit a fix soon and will post a note in this thread when it's ready.
2. Sounds like the Next button is waiting for an event that doesn't happen. I would guessit is waiting for a response from LMSInitialize and not getting it. 
For cases like this, I always open up the javascript debugger console to see if an error is being thrown. This will tell you if the server is sending back the response to LMSInitialize.
If there is no error, then next thing would be to go into the package and find out what triggers the Next button to be enabled - however, that might be tricky, depending on the vendor you use to create SCORM content.

**Comment by dhodges47** [comment]
It turns out I fixed the Suspend_data problem last December, so the Resume functionality should be working.

**Comment by NidhiAshree** [comment]
Sir, I checked latest one but still resume functionality not working .

**Comment by dhodges47** [comment]
If you send me the SCORM zip file I will upload it on my platform and try to determine why it isn't resuming.

**Comment by winstonpinto12** [comment]
Hi, 

Ihave completed some chapters now i have closed the window. Now when i launch the course its starting from the beginning again.
attached the scorm
[SL360_LMS_SCORM_1_2.zip](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/4793635/SL360_LMS_SCORM_1_2.zip)

**Comment by dhodges47** [comment]
I couldn't find the problem. Everything is working correctly on the LMS end. I passed the test and went to the very end. Your course recorded my score but left the lesson status as "incomplete".
And, as you said, it isn't restarting where I left off, even though it is saving suspend_data correctly to the LMS database. 
I turned on the debug option in your course but that didn't show me anything useful.
So, this remains un-solved.

**Comment by dhodges47** [comment]
Ok, this is fixed. The problem WAS on the LMS end, in the following javascript file:
/wwwroot/js/OutermostLMSV5.js. It wasn't returned the results of GetValue correctly to the SCORM module. You will have to replace this file in your own instance of this LMS. You don't have to change any SCORM modules.
