### ISSUE TITLE
Responsive HTML5 Output SCORM File with Quiz 

### ISSUE THREAD

**Issue by Kopal-LMS** [dhodges47/SCORM-LearningManagementSystem#16]
Thank you so much for your response.
I have downloaded the latest project and check SCORM file which having quiz is not opening on SCORM player. Quiz slide showing blank. I am attaching the SCORM file having quiz and publish the output in HTML5 format for responsive project, but the file is not loading on player, But I am viewing the file from physical location ,quiz is showing.
Please help me out from this issue.
![image](https://user-images.githubusercontent.com/66865599/89717281-7b1bcb00-d9d2-11ea-86aa-b789820656fb.png)
[Fluid_Box_Demo_Responsive.zip](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/5046032/Fluid_Box_Demo_Responsive.zip)
[QuizProjectV1.zip](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/5046034/QuizProjectV1.zip)

I have tried to upload non responsive project also, in which output format as SWF flash file format. It is working on SCORM player. But Adobe flash is going out from coming December. So we can use only HTML5 output format. Please resolve this issue.

Thank you so much for your valuable support.

**Comment by dhodges47** [comment]
I tried running both of the courses you attached.
Both of them are returning a fatal javascript error in a javascript file
(CPXHRLoader.js) that is part of Captivate.
(You can see the error console if you turn on your browser's debugging
tools).
If you google search on the error you get a lot of responses. The most
basic solution that I saw was "Upgrade to the latest version of Captivate".
In any case, it is a known error in Captivate, and so it doesn't seem to be
anything I can fix on the LMS side.

The error is:

> Cannot read property 'charAt' of undefined
> VM829:1264 Uncaught TypeError: Cannot read property 'charAt' of undefined
>     at cp.QuizState.readNumber (eval at e (CPXHRLoader.js:formatted:163),
> <anonymous>:1264:423)
>     at cp.QuizState.readString (eval at e (CPXHRLoader.js:formatted:163),
> <anonymous>:1266:34)
>     at cp.PlaybackController.restoreObjectsFromState (eval at e
> (CPXHRLoader.js:formatted:163), <anonymous>:1345:20)
>     at Function.cp.resumeValuesFromDataChunk (eval at e
> (CPXHRLoader.js:formatted:163), <anonymous>:1259:460)
>     at cp.PlaybackController.RestoreQuizState (eval at e
> (CPXHRLoader.js:formatted:163), <anonymous>:1386:35)
>     at Function.cp.NewQuizLibraryInit (eval at e
> (CPXHRLoader.js:formatted:163), <anonymous>:982:3)
>     at Function.cp.CPPreInit (eval at e (CPXHRLoader.js:formatted:163),
> <anonymous>:990:246)
>     at Function.cp.ContinueCPInit (eval at e
> (CPXHRLoader.js:formatted:163), <anonymous>:1935:33)
>     at LoadContent (eval at e (CPXHRLoader.js:formatted:163),
> <anonymous>:1258:439)
>     at InitializeExecuted (eval at e (CPXHRLoader.js:formatted:163),
> <anonymous>:1879:36)


I searched on "Cannot read property 'charAT' of undefined CPXHRLoader.js"

**Comment by Kopal-LMS** [comment]
Thank you so much for response on my query.
Yes I am getting the same error and report to Captivate team also  and I have received the below response from Captivate team.
Captivate team suggests, there is a problem in SCORM player.
![image](https://user-images.githubusercontent.com/66865599/89938061-96d1dc00-dc33-11ea-92fb-309d6605aa41.png)

I have also checked both project working on SCORM cloud. 
Please help me out from this issue.

**Comment by dhodges47** [comment]
I'm out of ideas at this point.
I can't find anything wrong with the LMS.
If I think of something I'll let you know.

**Comment by Kopal-LMS** [comment]
Hi Dhodges,

Hope you are doing good.
Did you find any solution on my above query. Because I am totally stuck on responsive SCORM file which having quiz.
Because Captivate team not giving any solution on this because the above SCORM output file working on SCORM Cloud.
Kindly help me out from this LMS issue.

Thanks you so much for your valuable support.
Looking forward to your reply.

Regards,
Kopal Rajpoot

**Comment by dhodges47** [comment]
I replied to you a few days ago.
I have not found any solution. I can't see any errors coming from the LMS.
The only error I see is coming from Articulate.
I'm sorry but I don't have any ideas on what could be the problem.

**Comment by Kopal-LMS** [comment]
Hi Dhodges,
Hope you are doing good. I have explored about the responsive project using Captivate, it is working on SCORM cloud. I have debug the source code and getting attached error while using it. Please find the error log with the same.
[default-20200818-000.log](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/5147140/default-20200818-000.log)
[default-20200820-000.log](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/5147141/default-20200820-000.log)
[default-20200821-000.log](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/5147142/default-20200821-000.log)
Attaching the responsive SCORM also.
[Fluid_Box_Demo_Responsive_test_with_quiz.zip](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/5147143/Fluid_Box_Demo_Responsive_test_with_quiz.zip)
[Quiz Project Ambika.zip](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/5147144/Quiz.Project.Ambika.zip)
Kindly upload in your LMS and debug, you will get the same issue.
Looking forward to your reply.
Regards,
Kopal Rajpoot

**Comment by dhodges47** [comment]
From your logs I see a lot of database problems. There may be an issue with your database set up. One problem I can fix on my side is from a residual field called "msrepl_tran_version" that is not used in this iteration. I have attached a script to allow nulls in that field, which will resolve some of the errors you are getting. 
[SCORMFix.sql.zip](https://github.com/dhodges47/SCORM-LearningManagementSystem/files/5156335/SCORMFix.sql.zip)

**Comment by dhodges47** [comment]
I think I fixed the problem with the Articulate Storyline quizes. Please update your solution with the latest commit, which is labelled "Bug fix for Articulate Storyline quizes". The fix is in the file "SCORMRuntimeHelper.cs". After you rebuild your solution, try the quiz again.

**Comment by Kopal-LMS** [comment]
Hi Dhodges,
Thank you so much for the great solution. Its really work. Now quiz is working.
One more query I have, I am not getting any interaction data in below highlighted tables.
![image](https://user-images.githubusercontent.com/66865599/92015189-0a1bc900-ed6e-11ea-9ae3-8e1a96cd3f5e.png)
Could you please suggests.

Thanks & Regards,
Kopal Rajpoot

**Comment by dhodges47** [comment]
Please obtain the latest commits - "Fix to cmi_objectives" and "Fix bug in cmi_interactions".  Then try again.

**Comment by Kopal-LMS** [comment]
Hi, Really appreciated your reply, its solve many problems. Thank you so much.
Now I am getting another issue and points analyzed on latest updated source code-
1.“[cmi_interactions]” table   data in Column “n_id”  is  not  saving properly . I think  n_id column refers the Question Name ,   but it always updated the question text only for first row  when user  select correct response .
While  student _response  save properly  in different rows (create new row corresponding to each  user response). 
 
![image](https://user-images.githubusercontent.com/66865599/92133406-f7fd6180-ee25-11ea-8f26-1dc1e3515f03.png)

2.	Data is not  saving in following table
•	SELECT * FROM [OpenSourceSCORMLMS].[dbo].[cmi_comment_from_learner]
•	SELECT * FROM [dbo].[cmi_student_preferences]
•	SELECT * FROM [dbo].[cmi_comment_from_lms]--blank
•	SELECT * FROM cmi_comment_from_learner--blank
![image](https://user-images.githubusercontent.com/66865599/92133767-6510f700-ee26-11ea-831c-d118feb8daeb.png)

Thank you so much for your support.

Regards,
Kopal

**Comment by dhodges47** [comment]
Please get the latest commit. It should solve the problem with cmi_interactions.
For cmi_comment_from_learner, cmi_comment_from_lms, cmi_comment_from_lms: Do you have a scorm module that sets these values? I don't have any way to test these, since none of the modules I have are calling the api for these values.

**Comment by Kopal-LMS** [comment]
Hi Dhodges,
Thank you so much for a valuable support. You have solved many issues where I was totally stucked.
Really appreciated for resolving the query. As per my last comment, I  dont have such SCORM file which sets the values in these tables cmi_comment_from_learner, cmi_comment_from_lms, cmi_comment_from_lm

Regards,
Kopal

**Comment by dhodges47** [comment]
Thanks Kopal. Because of your persistence I was able to identify and fix several bugs that had not been reported before, so I appreciate your help.
If I get a chance, I'll see if I can set up a test for the comment tables.
I am going to close this issue. If you come across anything else, please open a new issue.
Thanks again,
David
