### ISSUE TITLE
help me to run this program

### ISSUE THREAD

**Issue by loby970** [dhodges47/SCORM-LearningManagementSystem#2]
Hello
I download this program completely, and open it in visula studio 2017, but when I **build**  it I face a lot of errors such as this:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'adlcp_rootv1p2' could not be found (are you missing a using directive or an assembly reference?)	OpenSourceSCORMLMS	C:\Users\lobat.v\Downloads\scorm\SCORM-LearningManagementSystem-master\OpenSourceSCORMLMS\Helpers\SCORMUploadHelper.cs	1	N/A

please help me. 
I am begginer to using github.
Thank you

**Comment by Alibesharat** [comment]
Just rebuild the projects one by one from the top of Solution

**Comment by dhodges47** [comment]
Alibesharat is correct. You have to rebuild all the projects in order.
