### ISSUE TITLE
Newer version that does not rely on .net core 2.1?

### ISSUE THREAD

**Issue by TommySharpNZ** [dhodges47/SCORM-LearningManagementSystem#20]
Is there any chance of someone updating this to use a more recent version of .net core? I am having issues trying to get it to run at all on my development machine.

**Comment by dhodges47** [comment]
Sorry, I'm the original developer and I have moved on from eLearning and from the .Net platform, and have my hands full with other projects. Anyone who is interested is welcome to do the upgrade.
