### ISSUE TITLE
Issue with Loading The Index.html resource

### ISSUE THREAD

**Issue by jemraider21** [dhodges47/SCORM-LearningManagementSystem#22]
I have a few packages that I am testing out before I integrate the project with my main project. I can verify that the the uploading of the courses are successful and that the database updates accordingly, but when I try to launch these courses, I get a blank screen. Under the network tab, I see that a call is made to load the index.html file, but that resource is returning with a 404 error

**Comment by dhodges47** [comment]
This is a very common error. It means that the virtual folder you specified
in Appsettings isn't pointing to the actual content folder.
How to fix:
Look at the url in the network tab.
Does the folder it is referencing exist in your application?
If not, change the value in AppSettings to match the folder where you
actually store your content.

**Comment by jemraider21** [comment]
The above suggestion fixed my issue. I was zipping the folder instead of just the content inside of the folder and the program was confused to why the index file wasn't found
