### ISSUE TITLE
How to find user actual complete course or user close the window?

### ISSUE THREAD

**Issue by jasminrsolanki** [dhodges47/SCORM-LearningManagementSystem#24]
Hello

I have integrate this solution with my own project but when user complete course it is calling LMSFinish but the same method call for closing iframe so how i can identify user complete actual course or terminate?

**Comment by dhodges47** [comment]
It's hard to answer this without knowing about your project.
If you need realtime notifications you can add javascript to your page that
hosts the iFrame to react to the closing of the iFrame.
Or you can modify the LMSFinish code to send an event to your application,
or to award a completion certificate if they passed, or any other purpose.

In my production application, the user's course listing shows whether the
course is finished or in process or not started by reading  from the SCORM
database (cmi_core.exit and cmi_core.lesson_status).

**Comment by jasminrsolanki** [comment]
I have done using call stack of LMSFinish method in javascript 

Thanks
