### ISSUE TITLE
Last Resume not Working 

### ISSUE THREAD

**Issue by NidhiAshree** [dhodges47/SCORM-LearningManagementSystem#8]
I used your application as API  into our LMS ,   when we call the scorm player   then we are not able to start with last resume point , while lesson_location saved into our  table , but after LMS initialize  it is not call  for LMS get value .
And  also data not save into interactions and student Preferences  tables  .

**Comment by dhodges47** [comment]
If the SCORM object is not calling for the last resume point, that is the fault of the SCORM object itself. The code in my application does correctly return lesson_location when the SCORM asks for it.
I'm not sure about interactions and student preferences. If those are not being set by LMSSetValue, it should be straightforward someone to add them to the code.
